builds:
  -
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64
    ldflags:
      - -s -w
      - -X github.com/p2pquake/jmaxml-watcher/cmd.Version={{.Version}}
      - -X github.com/p2pquake/jmaxml-watcher/cmd.Commit={{.Commit}}
      - -X github.com/p2pquake/jmaxml-watcher/cmd.Date={{.Date}}

archives:
  -
    format: zip
    files:
      - README.md
      - LICENSE

